version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "demo-stack"
s3_bucket = "etrhthrthsrthstrhrsthtwrth"
s3_prefix = "demo-stack"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
